spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/login/oauth2/code/auth0
        provider:
          auth0:
            token-uri: https://${AUTH0_URL}/oauth/token
            authorization-uri: https://${AUTH0_URL}/authorize
            grant-type: client_credentials
            audience: https://${AUTH0_URL}/api/v2/
      resourceserver:
        auth0:
          # trailing slash is important!
          issuer-uri: https://${AUTH0_URL}/
        jwt:
          issuer-uri: https://${AUTH0_URL}/
          jwk-set-uri: https://${AUTH0_URL}/.well-known/jwks.json
